#!/bin/bash                                                                                                                                                                                                         
path=`pwd`
cd $path
git clone -b stable git@github.com:GerritCodeReview/git-repo.git repo
mkdir .repo
mv repo .repo/
.repo/repo/repo $@

